site_name: Jorge Diogo Ribeiro Personal Webpage
site_url: https://jorgedfr.github.io
site_author: Jorge Diogo Ribeiro

# Repository
repo_name: jorgedfr/jorgedfr.github.io
repo_url: https://github.com/jorgedfr/jorgedfr.github.io
edit_uri: edit/main/docs/

# Copyright
copyright: Copyright &copy; 2025 Jorge Diogo Ribeiro

plugins:
  - search

theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: jorgedfr
      primary: custom
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Red Hat Text
    code: JetBrains Mono
  #favicon: assets/logo/todo.svg
  #logo: assets/logo/todo.svg

# Additional configuration
extra:
  # generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/JorgeDFR
      name: GitHub @jorgedfr
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.com/JorgeDFR
      name: GitLab @jorgedfr
    - icon: fontawesome/brands/gitlab
      link: https://gitlab.inesctec.pt/jorge.d.ribeiro
      name: GitLab INESC TEC @jorge.d.ribeiro
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0009-0008-9373-982X
      name: ORCiD
    - icon: fontawesome/brands/google-scholar
      link: https://scholar.google.pt/citations?user=xp6I4DMAAAAJ&hl
      name: Google Scholar
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jorge-diogo-ribeiro
      name: LinkedIn
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCqGAuSvxXoLepWwcWZeTE8g
      name: YouTube Channel @JorgeDRibeiro

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.pathconverter:
      base_path: "jorgedfr/jorgedfr.github.io"
      relative_path: ""
      absolute: false
nav:
  - Home: index.md
  - CV: cv.md
  - Research: research.md
  - Projects: projects.md
  - Teaching: teaching.md
  - Publications: publications.md
  - Open-Source: open-source.md
  - Awards: awards.md
  - Tools:
    - tools/index.md
    - Operating System (OS):
        - tools/os/index.md
        - NVIDIA Drivers: tools/os/nvidia.md
        - Remote Access: tools/os/remote-access.md
        - Development Environment: tools/os/dev.md
    - Git: tools/git.md
    - Docker:
        - tools/docker/index.md
        - ROS: tools/docker/ros.md

extra_javascript:
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - stylesheets/extra.css